# theme: jekyll-theme-slate
title: Thomas Rackow
description: climate modelling and scicomm
remote_theme: daattali/beautiful-jekyll

# Your name to show in the footer
author: Thomas Rackow

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Resources:
    - AWI: "https://www.awi.de"
    - YOPP: "https://www.polarprediction.net"
  Author's home: "https://trackow.github.io"
  
  # --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "assets/img/trackow_400x400.jpg"

# By default, the image is cut into a circle. You can disable this behaviour here.
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image

# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  instagram: polarthomas
  twitter: thomas_rackow
  rss: false
#  linkedin: xxxxxxxx

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

#navbar-col: "#F5F5F5"
#navbar-text-col: "#404040"
#navbar-border-col: "#EAEAEA"
#page-col: "#FFFFFF"
#link-col: "#008AFF"
#hover-col: "#0085A1"
#footer-col: "#F5F5F5"
#footer-text-col: "#777777"
#footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"
